// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ELxC9DCBAMzCl5dprqpLj5zXCOWVMvQ',
    appId: '1:773733453612:android:bd41f00c05d2703dc12689',
    messagingSenderId: '773733453612',
    projectId: 'chat-app-54495',
    storageBucket: 'chat-app-54495.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDexCQdtVwfiFezMD4v-Yssckeb0HQa9io',
    appId: '1:773733453612:ios:17233c3b4b73290ac12689',
    messagingSenderId: '773733453612',
    projectId: 'chat-app-54495',
    storageBucket: 'chat-app-54495.appspot.com',
    androidClientId: '773733453612-g4s3q5urn9paeuekc82uvse20vvl0tsp.apps.googleusercontent.com',
    iosClientId: '773733453612-p3ldnev8bttu06c4ckb0v71lh7s5pd57.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
